apiVersion: v1
kind: Service
metadata:
  name: canal-admin
  labels:
    app: canal-admin
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: canal-admin
