apiVersion: v2
appVersion: 2.6.1
description: Ververica Platform is the enterprise stream processing platform by the
  original creators of Apache Flink®.
home: https://www.ververica.com/
icon: https://charts.ververica.com/vvp-logo.png
keywords:
- ververica
- flink
kubeVersion: '>= 1.11.0-0'
maintainers:
- email: platform@ververica.com
  name: Ververica Support
name: ververica-platform
version: 5.2.1
