version: 1.0
name: abm-maven
variables:
  DOCKERFILE_PATH: /
  TAG: latest
machine:
  standard:
    abm_machines:
      - default
scripts:
  - sudo docker build --no-cache -t reg.docker.alibaba-inc.com/abm-aone/maven:{{TAG}} -f Dockerfile .
artifacts:
  images:
    - reg.docker.alibaba-inc.com/abm-aone/maven:{{TAG}}
notifications:
  email:
    - qiuqiang.qq@alibaba-inc.com
    - yaoxing.gyx@alibaba-inc.com
