# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: canal-adapter-startup-conf
  labels:
    app: canal-adapter
    release: {{ .Release.Name }}
data:
  adapter-startup.sh: |
    #!/bin/bash
    cat > /home/admin/canal-adapter/conf/application.yml <<- EOF
    server:
      port: {{ .Values.serverPort }}
    spring:
      jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null

    canal.conf:
      mode: rocketMQ #tcp kafka rocketMQ rabbitMQ
      flatMessage: {{ .Values.rocketmq.flatMessage }}
      zookeeperHosts:
      syncBatchSize: {{ .Values.rocketmq.syncBatchSize }}
      retries: {{ .Values.rocketmq.retries }}
      timeout:
      accessKey:
      secretKey:
      consumerProperties:
        # rocketMQ consumer
        rocketmq.namespace:
        rocketmq.namesrv.addr: {{ .Values.rocketmq.servers }}
        rocketmq.batch.size: {{ .Values.rocketmq.syncBatchSize }}
        rocketmq.enable.message.trace: {{ .Values.rocketmq.messageTrace }}
        rocketmq.customized.trace.topic: {{ .Values.rocketmq.traceTopic }}
        rocketmq.access.channel:
        rocketmq.subscribe.filter:

      srcDataSources:
        {{ .Values.srcDataSources.name }}:
          url: {{ .Values.srcDataSources.url }}
          username: {{ .Values.srcDataSources.username }}
          password: {{ .Values.srcDataSources.password }}

      canalAdapters:
        - instance: {{ .Values.rocketmq.topic }} # canal instance Name or mq topic name
          groups:
            - groupId: {{ .Values.canalAdapterRdbGroup.groupId }}
              outerAdapters:
              - name: logger
              - name: rdb
                key: {{ .Values.canalAdapterRdbGroup.key }}
                properties:
                  jdbc.driverClassName: {{ .Values.canalAdapterRdbGroup.properties.driverClassName }}
                  jdbc.url: {{ .Values.canalAdapterRdbGroup.properties.url }}
                  jdbc.username: {{ .Values.canalAdapterRdbGroup.properties.username }}
                  jdbc.password: {{ .Values.canalAdapterRdbGroup.properties.password }}
                  threads: {{ .Values.canalAdapterRdbGroup.properties.threads }}

    adapter.conf:
      datasourceConfigs:
        {{ .Values.srcDataSources.name }}:
          url: {{ .Values.srcDataSources.url }}
          username: {{ .Values.srcDataSources.username }}
          password: {{ .Values.srcDataSources.password }}
      adapterConfigs:
      - rdb/sreworks_team.yml
      - rdb/sreworks_team_account.yml
      - rdb/sreworks_team_user.yml
      - rdb/sreworks_cluster.yml
      - rdb/sreworks_cluster_resource.yml
      - rdb/sreworks_app.yml
      - rdb/sreworks_app_component.yml
      - rdb/sreworks_app_component_instance.yml
      - rdb/sreworks_app_instance.yml
      - rdb/sreworks_test.yml
    EOF

    cat > /home/admin/canal-adapter/conf/rdb/sreworks_team.yml <<- EOF
    dataSourceKey: {{ .Values.srcDataSources.name }}
    destination: {{ .Values.rocketmq.topic }}
    groupId: {{ .Values.canalAdapterRdbGroup.groupId }}
    outerAdapterKey: {{ .Values.canalAdapterRdbGroup.key }}
    concurrent: true
    dbMapping:
      database: sreworks
      table: team
      targetTable: team
      targetPk:
        id: id
      mapAll: true
    EOF

    cat > /home/admin/canal-adapter/conf/rdb/sreworks_team_account.yml <<- EOF
    dataSourceKey: {{ .Values.srcDataSources.name }}
    destination: {{ .Values.rocketmq.topic }}
    groupId: {{ .Values.canalAdapterRdbGroup.groupId }}
    outerAdapterKey: {{ .Values.canalAdapterRdbGroup.key }}
    concurrent: true
    dbMapping:
      database: sreworks
      table: team_account
      targetTable: team_account
      targetPk:
        id: id
      mapAll: true
    EOF

    cat > /home/admin/canal-adapter/conf/rdb/sreworks_team_user.yml <<- EOF
    dataSourceKey: {{ .Values.srcDataSources.name }}
    destination: {{ .Values.rocketmq.topic }}
    groupId: {{ .Values.canalAdapterRdbGroup.groupId }}
    outerAdapterKey: {{ .Values.canalAdapterRdbGroup.key }}
    concurrent: true
    dbMapping:
      database: sreworks
      table: team_user
      targetTable: team_user
      targetPk:
        id: id
      mapAll: true
    EOF

    cat > /home/admin/canal-adapter/conf/rdb/sreworks_cluster.yml <<- EOF
    dataSourceKey: {{ .Values.srcDataSources.name }}
    destination: {{ .Values.rocketmq.topic }}
    groupId: {{ .Values.canalAdapterRdbGroup.groupId }}
    outerAdapterKey: {{ .Values.canalAdapterRdbGroup.key }}
    concurrent: true
    dbMapping:
      database: sreworks
      table: cluster
      targetTable: cluster
      targetPk:
        id: id
      mapAll: true
    EOF

    cat > /home/admin/canal-adapter/conf/rdb/sreworks_cluster_resource.yml <<- EOF
    dataSourceKey: {{ .Values.srcDataSources.name }}
    destination: {{ .Values.rocketmq.topic }}
    groupId: {{ .Values.canalAdapterRdbGroup.groupId }}
    outerAdapterKey: {{ .Values.canalAdapterRdbGroup.key }}
    concurrent: true
    dbMapping:
      database: sreworks
      table: cluster_resource
      targetTable: cluster_resource
      targetPk:
        id: id
      mapAll: true
    EOF

    cat > /home/admin/canal-adapter/conf/rdb/sreworks_app.yml <<- EOF
    dataSourceKey: {{ .Values.srcDataSources.name }}
    destination: {{ .Values.rocketmq.topic }}
    groupId: {{ .Values.canalAdapterRdbGroup.groupId }}
    outerAdapterKey: {{ .Values.canalAdapterRdbGroup.key }}
    concurrent: true
    dbMapping:
      database: sreworks
      table: app
      targetTable: app
      targetPk:
        id: id
      mapAll: true
    EOF

    cat > /home/admin/canal-adapter/conf/rdb/sreworks_app_component.yml <<- EOF
    dataSourceKey: {{ .Values.srcDataSources.name }}
    destination: {{ .Values.rocketmq.topic }}
    groupId: {{ .Values.canalAdapterRdbGroup.groupId }}
    outerAdapterKey: {{ .Values.canalAdapterRdbGroup.key }}
    concurrent: true
    dbMapping:
      database: sreworks
      table: app_component
      targetTable: app_component
      targetPk:
        id: id
      mapAll: true
    EOF

    cat > /home/admin/canal-adapter/conf/rdb/sreworks_app_component_instance.yml <<- EOF
    dataSourceKey: {{ .Values.srcDataSources.name }}
    destination: {{ .Values.rocketmq.topic }}
    groupId: {{ .Values.canalAdapterRdbGroup.groupId }}
    outerAdapterKey: {{ .Values.canalAdapterRdbGroup.key }}
    concurrent: true
    dbMapping:
      database: sreworks
      table: app_component_instance
      targetTable: app_component_instance
      targetPk:
        id: id
      mapAll: true
    EOF

    cat > /home/admin/canal-adapter/conf/rdb/sreworks_app_instance.yml <<- EOF
    dataSourceKey: {{ .Values.srcDataSources.name }}
    destination: {{ .Values.rocketmq.topic }}
    groupId: {{ .Values.canalAdapterRdbGroup.groupId }}
    outerAdapterKey: {{ .Values.canalAdapterRdbGroup.key }}
    concurrent: true
    dbMapping:
      database: sreworks
      table: app_instance
      targetTable: app_instance
      targetPk:
        id: id
      mapAll: true
    EOF

    cat > /home/admin/canal-adapter/conf/rdb/sreworks_test.yml <<- EOF
    dataSourceKey: {{ .Values.srcDataSources.name }}
    destination: {{ .Values.rocketmq.topic }}
    groupId: {{ .Values.canalAdapterRdbGroup.groupId }}
    outerAdapterKey: {{ .Values.canalAdapterRdbGroup.key }}
    concurrent: true
    dbMapping:
      database: sreworks
      table: test
      targetTable: test
      targetPk:
        id: id
      mapAll: true
    EOF


    current_path=`pwd`
    case "`uname`" in
        Linux)
        bin_abs_path=$(readlink -f $(dirname $0))
        ;;
      *)
        bin_abs_path=`cd $(dirname $0); pwd`
        ;;
    esac
    base=${bin_abs_path}/..
    export LANG=en_US.UTF-8
    export BASE=$base

    if [ -f $base/bin/adapter.pid ] ; then
      echo "found adapter.pid , Please run stop.sh first ,then startup.sh" 2>&2
        exit 1
    fi

    if [ ! -d $base/logs ] ; then
      mkdir -p $base/logs
    fi

    ## set java path
    if [ -z "$JAVA" ] ; then
      JAVA=$(which java)
    fi

    ALIBABA_JAVA="/usr/alibaba/java/bin/java"
    TAOBAO_JAVA="/opt/taobao/java/bin/java"
    if [ -z "$JAVA" ]; then
      if [ -f $ALIBABA_JAVA ] ; then
        JAVA=$ALIBABA_JAVA
      elif [ -f $TAOBAO_JAVA ] ; then
        JAVA=$TAOBAO_JAVA
      else
        echo "Cannot find a Java JDK. Please set either set JAVA or put java (>=1.5) in your PATH." 2>&2
        exit 1
      fi
    fi

    case "$#"
    in
    0 )
      ;;
    2 )
      if [ "$1" = "debug" ]; then
        DEBUG_PORT=$2
        DEBUG_SUSPEND="n"
        JAVA_DEBUG_OPT="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,address=$DEBUG_PORT,server=y,suspend=$DEBUG_SUSPEND"
      fi
      ;;
    * )
      echo "THE PARAMETERS MUST BE TWO OR LESS.PLEASE CHECK AGAIN."
      exit;;
    esac

    str=`file -L $JAVA | grep 64-bit`
    if [ -n "$str" ]; then
      JAVA_OPTS="-server -Xms2048m -Xmx3072m -Xmn1024m -XX:SurvivorRatio=2 -XX:PermSize=96m -XX:MaxPermSize=256m -Xss256k -XX:-UseAdaptiveSizePolicy -XX:MaxTenuringThreshold=15 -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSCompactAtFullCollection -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError"
    else
      JAVA_OPTS="-server -Xms1024m -Xmx1024m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:MaxPermSize=128m "
    fi

    JAVA_OPTS=" $JAVA_OPTS -Djava.awt.headless=true -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8"
    ADAPTER_OPTS="-DappName=canal-adapter"

    for i in $base/lib/*;
        do CLASSPATH=$i:"$CLASSPATH";
    done

    CLASSPATH="$base/conf:$CLASSPATH";

    echo "cd to $bin_abs_path for workaround relative path"
    cd $bin_abs_path

    echo CLASSPATH :$CLASSPATH
    $JAVA $JAVA_OPTS $JAVA_DEBUG_OPT $ADAPTER_OPTS -classpath .:$CLASSPATH com.alibaba.otter.canal.adapter.launcher.CanalAdapterApplication 1>>/dev/null 2>&1 &
    echo $! > $base/bin/adapter.pid

    echo "cd to $current_path for continue"
    cd $current_path

