apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: canal-adapter
    release: {{ .Release.Name }}
  name: canal-adapter
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: canal-adapter
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: canal-adapter
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: canal-adapter
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["/bin/bash","-c","/home/admin/canal-adapter/bin/startup.sh && tail -F logs/adapter/adapter.log"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
          - mountPath: /home/admin/canal-adapter/bin/startup.sh
            name: adapter-startup
            subPath: adapter-startup.sh

      dnsPolicy: ClusterFirst
      restartPolicy: Always

      volumes:
        - configMap:
            defaultMode: 0777
            name: canal-adapter-startup-conf
          name: adapter-startup

      securityContext:
        runAsUser: 0
