{{- if eq .Values.installMode "default" -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ template "dataops.namespace" . }}

---

apiVersion: v1
kind: Namespace
metadata:
  name: {{ template "aiops.namespace" . }}

{{- end -}}
