t-tesla-frontend-manager:
  pkgpara:
    DOCKER: reg.docker.alibaba-inc.com/teslaenv/node_env
t-tesla-frontend-manager-ApsaraStack-V38:
  pkgpara:
    DOCKER: reg.docker.alibaba-inc.com/teslaenv/node_env
t-tesla-frontend-manager-OXS:
  pkgpara:
    DOCKER: reg.docker.alibaba-inc.com/teslaenv/node_env
t-tesla-frontend-manager-Standalone:
  pkgpara:
    DOCKER: reg.docker.alibaba-inc.com/teslaenv/node_env
t-tesla-frontend-manager-Standalone-S01:
  pkgpara:
    DOCKER: reg.docker.alibaba-inc.com/teslaenv/node_env
