componentType: K8S_MICROSERVICE
componentName: elasticsearch
options:
  containers:
    - ports:
        - containerPort: 7001
      name: server
      build:
        repoUrl: https://helm.elastic.co
        chartName: elasticsearch
        chartVersion: 7.13.0

  env:
    - DB_HOST
    - DB_PORT
    - DB_USER
    - DB_PASSWORD
    - DB_NAME
