
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-abm-io-v1-job
  failurePolicy: Fail
  name: mjob.kb.io
  rules:
  - apiGroups:
    - apps.abm.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobs
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-abm-io-v1-microservice
  failurePolicy: Fail
  name: mmicroservice.kb.io
  rules:
  - apiGroups:
    - apps.abm.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - microservices

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-abm-io-v1-job
  failurePolicy: Fail
  name: vjob.kb.io
  rules:
  - apiGroups:
    - apps.abm.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobs
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-abm-io-v1-microservice
  failurePolicy: Fail
  name: vmicroservice.kb.io
  rules:
  - apiGroups:
    - apps.abm.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - microservices
