# Default values for canal-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

serverPort: 8081

image:
  repository: "liuyujie/canal-adapter"
  pullPolicy: IfNotPresent
  tag: "v1.1.5"

rocketmq:
  servers: "name-server-service.default.svc.cluster.local:9876"
  retries: 0
  topic: "sreworks_data_topic"
  syncBatchSize: 1000
  flatMessage: true
  messageTrace: false
  traceTopic:

srcDataSources:
  name: "sreworks"
  url: "jdbc:mysql://appmanager-mysql.default.svc.cluster.local:3306/sreworks?useUnicode=true&characterEncoding=UTF-8"
  username: "canal"
  password: "canal"

canalAdapterRdbGroup:
  groupId: "sreworks_group"
  key: "sreworks_rdb"
  properties:
    driverClassName: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://data-mysql.data.svc.cluster.local:3306/sreworks?useUnicode=true&characterEncoding=UTF-8"
    username: "root"
    password: "root"
    threads: 1









