
### server config
server:
  port: 7001

### management config
management:
  server:
    port: 7002
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway,admin,view


### spring application config
spring:
  application:
    name: tesla-gateway
  cloud:
    ### 网关配置
    gateway:
      httpclient:
        response-timeout: 300s
        connect-timeout: 3000 # 连接超时时间3s
        pool:
          type: disabled
          name: gateway-connection-pool
      discovery:
        locator:
          enabled: false # 如果开启，将自动将服务注册上的所有服务都可以通过网关访问
      x-forwarded:
        prefix-enabled: false # 禁用，需要定制支持doc
      routes:
        - id: product-ops-flower
          uri: ${diamond.product.ops.flower.uri}
          predicates:
            - Host=${diamond.product.ops.flower.host}
          order: 50
        - id: gateway-forward-env-daily
          uri: http://gateway-daily.tesla.alibaba-inc.com
          predicates:
            - Header=X-GATEWAY-FORWARD-ENV, daily
          order: 10
        - id: gateway-forward-env-daily2
          uri: http://gateway-daily2.tesla.alibaba-inc.com
          predicates:
            - Header=X-GATEWAY-FORWARD-ENV, daily2
          order: 10
        - id: gateway-forward-env-pre
          uri: http://gateway-pre.tesla.alibaba-inc.com
          predicates:
            - Header=X-GATEWAY-FORWARD-ENV, pre
          order: 10

    nacos: # nacos 配置
      discovery:
        namespace: ${diamond.nacos.namespace}
        server-addr: ${diamond.nacos.server-name}
        watch-delay: 30000 #30s
      config:
        server-addr: ${diamond.nacos.server-name}
        namespace: ${diamond.nacos.namespace}

  diamond:
    data-id: com.alibaba.tesla:gateway.properties
    group-id: DEFAULT_GROUP
    cloud:
      refresh:
        enabled: true
  redis:
    database: ${diamond.redis.database}
    host: ${diamond.redis.host}
    password: ${diamond.redis.pwd}
    port: ${diamond.redis.port}
    timeout: 15000
  resources:
    add-mappings: false



  eagleeye:
    enabled: false

### tesla config
tesla:
  env: ${diamond.env}
  region: ${diamond.region}
  auto-online: false #手动去触发上线，避免刚开始启动时，路由未完全初始化，出现No handler
  config:
    sentry:
      dsn: http://e4646fc5009044d0aa6cc0ace385a730@sentry.tesla.alibaba-inc.com/43
      env: ${diamond.env}
    gateway:
      admin-token: af82d2e7-a8ec-48ac-8c1c-b6048cd8c64a
      auth-address: ${diamond.auth-address}
      authCookieKey: 0d260eab-4760-4bcd-a0a3-6db6b7a3053e
      authCookieName: ${diamond.tesla.authCookieName}
      jwt-secret: ${diamond.tesla.jwtSecret}
      tesla-auth-app: teslaweb
      tesla-auth-key: b2cbbe79-b832-4b79-aabc-6471c1842e32
      store-diamond-data-id: com.alibaba.tesla.gateway.route-config
      store-diamond-group: tesla-gateway
      store-nacos-data-id: tesla.gateway.route.config
      store-nacos-group: DEFAULT_GROUP
      store-nacos-namespace: 5d6df58b-79b3-4c18-ac5a-94cad555c906
      store-nacos-addr: nacos-daily.tesla.alibaba-inc.com:80
      auth-whitelist-diamond-data-id: com.alibaba.tesla.gateway.auth-whitelist
      auth-whitelist-diamond-group: tesla-gateway
      allow-cros-domain: ${diamon.allow.cros.domain}
      auth-redirect-url: "https://tesladaily.alibaba-inc.com/api-proxy/auth/login"

### log config, 开启debug方便排查问题
#logging:
#  level:
#    org.springframework.cloud.gateway: trace
#    org.springframework.http.server.reactive: debug
#    org.springframework.web.reactive: debug
#    reactor.ipc.netty: debug

##临时解决环境问题
env: ${diamond.env}