
### server config
server:
  port: 7001

### management config
management:
  server:
    port: 7002
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway,admin,view

project:
  name: tesla-gateway




### spring application config
spring:
  application:
    name: tesla-gateway
  cloud:
    ### 网关配置
    gateway:
      httpclient:
        response-timeout: 300s
        connect-timeout: 6000 # 连接超时时间5s
        pool:
          type: disabled
          name: gateway-connection-pool

      discovery:
        locator:
          enabled: false # 如果开启，将自动将服务注册上的所有服务都可以通过网关访问
      routes:
        - id: product-ops
          uri: ${diamond.product.ops.uri}
          predicates:
            - Host=${diamond.product.ops.host}
          order: 50
        - id: prod-productops-env-daily-internal
          uri: http://10.150.74.33:80
          predicates:
            - Host=prod-productops-env-daily.tesla.alibaba-inc.com
        - id: prod-productops-env-daily-flower-internal
          uri: http://10.150.74.35:80
          predicates:
            - Host=prod-productops-env-daily-flower.tesla.alibaba-inc.com
        - id: prod-productops-env-pre-internal
          uri: http://11.141.158.181:80
          predicates:
            - Host=prod-productops-env-pre.tesla.alibaba-inc.com
        - id: prod-productops-env-pre-flower-internal
          uri: http://11.141.159.24:80
          predicates:
            - Host=prod-productops-env-pre-flower.tesla.alibaba-inc.com
        - id: prod-productops-env-prod-internal
          uri: http://11.141.157.211:80
          predicates:
            - Host=prod-productops-env-prod.tesla.alibaba-inc.com
        - id: prod-productops-env-prod-flower-internal
          uri: http://11.226.8.26:80
          predicates:
            - Host=prod-productops-env-prod-flower.tesla.alibaba-inc.com

        - id: gateway-forward-env-daily
          uri: http://gateway-daily.tesla.alibaba-inc.com
          predicates:
            - Header=X-GATEWAY-FORWARD-ENV, daily
          order: 10
        - id: gateway-forward-env-daily2
          uri: http://gateway-daily2.tesla.alibaba-inc.com
          predicates:
            - Header=X-GATEWAY-FORWARD-ENV, daily2
          order: 10
        - id: gateway-forward-env-pre
          uri: http://gateway-pre.tesla.alibaba-inc.com
          predicates:
            - Header=X-GATEWAY-FORWARD-ENV, pre
          order: 10

    nacos: # nacos 配置
      discovery:
        namespace: ${diamond.nacos.namespace}
        server-addr: ${diamond.nacos.server-name}
        watch-delay: 30000 #30s
      config:
        server-addr: ${diamond.nacos.server-name}
        namespace: ${diamond.nacos.namespace}

  diamond:
    data-id: com.alibaba.tesla:gateway.properties
    group-id: DEFAULT_GROUP
    cloud:
      refresh:
        enabled: true
  redis:
    database: ${diamond.redis.database}
    host: ${diamond.redis.host}
    password: ${diamond.redis.pwd}
    port: ${diamond.redis.port}
    timeout: 15000
  resources:
    add-mappings: false


  eagleeye:
    enabled: false

### tesla config
tesla:
  env: ${diamond.env}
  region: ${diamond.region}
  config:
    sentry:
      dsn: http://e4646fc5009044d0aa6cc0ace385a730@sentry.tesla.alibaba-inc.com/43
      env: ${diamond.env}
    gateway:
      admin-token: af82d2e7-a8ec-48ac-8c1c-b6048cd8c64a
      auth-address: ${diamond.auth-address}
      authCookieKey: 0d260eab-4760-4bcd-a0a3-6db6b7a3053e
      jwt-secret: ${diamond.tesla.jwtSecret}
      store-diamond-data-id: com.alibaba.tesla.gateway.route-config
      store-diamond-group: tesla-gateway
      store-nacos-data-id: tesla.gateway.route.config
      store-nacos-group: DEFAULT_GROUP
      sls:
        log-store: ${diamond.sls.log-store}
        project: ${diamond.sls.project}
        end-point: ${diamond.sls.end-point}
        access-key-id: ${diamond.sls.access-key-id}
        access-key-secret: ${diamond.sls.access-key-secret}
      store-nacos-namespace: 5d6df58b-79b3-4c18-ac5a-94cad555c906
      store-nacos-addr: nacos-daily.tesla.alibaba-inc.com:80
      auth-redirect-url: "https://tesla.alibaba-inc.com/api-proxy/auth/login"



### log config, 开启debug方便排查问题
#logging:
#  level:
#    org.springframework.cloud.gateway: trace
#    org.springframework.http.server.reactive: debug
#    org.springframework.web.reactive: debug
#    reactor.ipc.netty: debug

