version: 1.0
name: abm-appmanager-operator
variables:
  IS_DOCKER: 1
  cpuArch: "x86_64"
machine:
  standard:
    abm_machines:
      - default
scripts:
  - sh ./fw_build.sh "{{FW_BRANCH_NAME}}" "{{cpuArch}}"
artifacts:
  images:
    - reg.docker.alibaba-inc.com/abm-aone/abm-appmanager-operator:{{FW_BRANCH_NAME}}_{{cpuArch}}
notifications:
  email:
    - yaoxing.gyx@alibaba-inc.com
