componentType: INTERNAL_ADDON
componentName: productopsv2
options: 
  endpoint: prod-sreworks-flycore-paas-action
---
componentType: INTERNAL_ADDON
componentName: appmeta
options: {}
---
componentType: INTERNAL_ADDON
componentName: developmentmeta
options: {}
