t-tesla-server-authproxy:
  pkgpara:
    DOCKER: 1
t-tesla-server-authproxy-ApsaraStack-V38:
  pkgpara:
    DOCKER: 1
t-tesla-server-authproxy-OXS:
  pkgpara:
    DOCKER: 1
t-tesla-server-authproxy-Standalone:
  pkgpara:
    DOCKER: 1
t-tesla-server-authproxy-Standalone-S01:
  pkgpara:
    DOCKER: 1
