version: 1.0
name: paas-nacos
variables:
  DOCKERFILE_PATH: "/"
  IMAGE_PREFIX: "reg.docker.alibaba-inc.com/abm-aone/paas-nacos"
  IMAGE_NAME: "paas-nacos"
  cpuArch: "x86_64"
machine:
  standard:
    abm_machines:
      - default
scripts:
  - ./fw_build.sh "{{IMAGE_NAME}}" "{{FW_BRANCH_NAME}}" "{{cpuArch}}"
artifacts:
  images:
    - "{{IMAGE_PREFIX}}:{{FW_BRANCH_NAME}}_{{cpuArch}}"
    - "{{IMAGE_PREFIX}}-db-migration:{{FW_BRANCH_NAME}}_{{cpuArch}}"
    - "{{IMAGE_PREFIX}}-config-init:{{FW_BRANCH_NAME}}_{{cpuArch}}"
notifications:
  email:
    - yaoxing.gyx@alibaba-inc.com
