# Default values for canal-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 2

image:
  repository: "canal/canal-server"
  pullPolicy: IfNotPresent
  tag: "v1.1.5"

canalAdmin:
  address: "canal-admin.data.svc.cluster.local:31628"
  port: 11110
  user: "admin"
  password: "6BB4837EB74329105EE4568DDA7DC67ED2CA2AD9"

zookeeper:
  servers: "appmanager-zookeeper.default.svc.cluster.local:2181"

rocketmq:
  servers: "name-server-service.default.svc.cluster.local:9876"
  retries: 1
  producerGroup: "Canal-Producer"
  topic: "sreworks_data_topic"

tsdb:
  enable: true
  url: "jdbc:mysql://data-mysql.data.svc.cluster.local:3306/canal_tsdb"
  username: "root"
  password: "root"

syncMysql:
  slaveId: 1111
  address: "appmanager-mysql.default.svc.cluster.local:3306"
  username: "root"
  password: "bguwsawqm6k"
  connectionCharset: "UTF-8"

syncFilter:
  regex: "sreworks\\..*"
  blackRegex: "sreworksappmanager\\..*"

mysql: {}
