t-tesla-server-gateway:
  pkgpara:
    DOCKER: 1
t-tesla-server-gateway-ApsaraStack-V38:
  pkgpara:
    DOCKER: 1
t-tesla-server-gateway-OXS:
  pkgpara:
    DOCKER: 1
t-tesla-server-gateway-Standalone:
  pkgpara:
    DOCKER: 1
t-tesla-server-gateway-Standalone-S01:
  pkgpara:
    DOCKER: 1
